---
# tasks file for rhel_chrome
- name: "Download Google Chrome RPM {{ CHROME_REPO }}{{ CHROME_PACKAGE_NAME }} to {{ LOCAL_RPM_PATH }}{{ CHROME_PACKAGE_NAME }}"
  get_url:
    url: "{{ CHROME_REPO }}{{ CHROME_PACKAGE_NAME }}"
    dest: "{{ LOCAL_RPM_PATH }}{{ CHROME_PACKAGE_NAME }}"
    mode: 0440

- name: "Install chrome dependancies "
  yum:
    name: "{{ item }}"
    state: latest
  with_items: "{{ CHROME_DEPS }}"
  become: yes

- name: "Install Chrome from file {{ LOCAL_RPM_PATH }}{{ CHROME_PACKAGE_NAME }}"
  yum:
    name: "{{ LOCAL_RPM_PATH }}{{ CHROME_PACKAGE_NAME }}"
    state: latest
  become: yes
